{{- if .Values.config.server.admin.admin_token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yvonne.fullname" . }}-secrets
  labels:
    {{- include "yvonne.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.config.server.admin.admin_token | quote }}
  {{- if .Values.config.server.mcp.token }}
  mcp-token: {{ .Values.config.server.mcp.token | quote }}
  {{- end }}
  {{- if .Values.config.auth.jwt.secret }}
  jwt-secret: {{ .Values.config.auth.jwt.secret | quote }}
  {{- end }}
{{- end }}
